# GitHub Actions Workflow to send a daily Telegram message
# This workflow runs every day at 12:00 AM Bangladesh Time (18:00 UTC)

name: Send Daily Telegram Plan

on:
  # Schedule to run at 18:00 UTC, which is 12:00 AM in Bangladesh (UTC+6)
  schedule:
    - cron: '0 18 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python script to send the message
      - name: Run Python script
        env:
          # These secrets must be configured in your GitHub repository settings
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
        run: python main.py
